apiVersion: v1
kind: Service
metadata:
  name: sb-helm
  labels:
    # Enables "zarf connect wordpress-blog"
    zarf.dev/connect-name: sb-helm
  annotations:
    zarf.dev/connect-description: "The spring boot helm demo app"
spec:
  selector:
    app.kubernetes.io/instance: ewyles-spring-boot
    app.kubernetes.io/name: springboot-demoweb
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
